// <auto-generated />
using System;
using CleaningTracking.DataAccess.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleaningTracking.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CleaningTracking.Core.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("CleaningTracking.Core.Entities.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("CleaningTracking.Core.Entities.QRCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("QRCodeValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QRImagePath")
                        .HasColumnType("longtext");

                    b.Property<int>("RestroomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestroomId")
                        .IsUnique();

                    b.ToTable("QRCodes");
                });

            modelBuilder.Entity("CleaningTracking.Core.Entities.Restroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsClean")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RestroomName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Restrooms");
                });

            modelBuilder.Entity("CleaningTracking.Core.Entities.Floor", b =>
                {
                    b.HasOne("CleaningTracking.Core.Entities.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("CleaningTracking.Core.Entities.QRCode", b =>
                {
                    b.HasOne("CleaningTracking.Core.Entities.Restroom", "Restroom")
                        .WithOne("QRCode")
                        .HasForeignKey("CleaningTracking.Core.Entities.QRCode", "RestroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restroom");
                });

            modelBuilder.Entity("CleaningTracking.Core.Entities.Restroom", b =>
                {
                    b.HasOne("CleaningTracking.Core.Entities.Floor", "Floor")
                        .WithMany("Restrooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("CleaningTracking.Core.Entities.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("CleaningTracking.Core.Entities.Floor", b =>
                {
                    b.Navigation("Restrooms");
                });

            modelBuilder.Entity("CleaningTracking.Core.Entities.Restroom", b =>
                {
                    b.Navigation("QRCode");
                });
#pragma warning restore 612, 618
        }
    }
}
